import { Inter } from 'next/font/google'
import Script from 'next/script'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'HomeProtein',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Script strategy='afterInteractive' src='https://www.googletagmanager.com/gtag/js?id=G-SXXTS7KV2L' />
      <Script strategy='afterInteractive' id='google-analytics'>
        {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', 'G-SXXTS7KV2L');
        `}
      </Script>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
